<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMKN 1 Garut | Sekolah Kejuruan Masa Depan</title>
    <meta name="description" content="SMKN 1 Garut membentuk generasi terampil, berkarakter, dan siap menghadapi dunia industri.">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="school-landing">
    <div class="landing-orb landing-orb-one"></div><div class="landing-orb landing-orb-two"></div>
    <header class="landing-nav centered-nav" data-landing-nav>
        <nav class="landing-links nav-links-left" aria-label="Navigasi utama"><a href="#beranda">Tentang</a><a href="#jurusan">Jurusan</a><a href="#fasilitas">Fasilitas</a></nav>
        <a class="landing-brand centered-brand" href="#beranda" aria-label="SMKN 1 Garut"><img src="/images/image-2.png" alt="Logo SMKN 1 Garut"><span><strong>SMKN 1 Garut</strong><small>Motekar Wibawa Mukti</small></span></a>
        <div class="nav-actions"><a class="nav-ppdb" href="#ppdb">PPDB <span>↗</span></a><a class="nav-portal" href="{{ route('login') }}">Portal siswa</a><a class="nav-contact" href="#kontak" aria-label="Kontak sekolah">Kontak</a></div>
        <button class="landing-menu" type="button" aria-label="Buka menu" aria-expanded="false" data-landing-menu>☰</button>
    </header>

    <main>
        <section id="beranda" class="landing-wrap landing-hero hero-banner">
            <div class="hero-copy"><p class="hero-badge">SMKN 1 GARUT <span>•</span> MOTEKAR WIBAWA MUKTI</p><p class="landing-kicker"><span></span> Sekolah kejuruan negeri di jantung Garut</p><h1>Ruang belajar yang<br><em>punya arah.</em></h1><p class="hero-lead">SMKN 1 Garut adalah rumah bagi anak muda yang ingin mengubah rasa ingin tahu menjadi keahlian. Sejak 1951, kami menghubungkan pendidikan karakter, kompetensi vokasi, dan kebutuhan dunia industri.</p><div class="hero-actions"><a class="landing-button landing-button-primary" href="#jurusan">Jelajahi jurusan <span>↓</span></a><a class="landing-button hero-button-light" href="#ppdb">Portal PPDB <span>↗</span></a></div></div>
            <div class="hero-banner-stats" aria-label="Statistik SMKN 1 Garut"><div><strong>10</strong><span>Kompetensi<br>Keahlian</span></div><div><strong>120+</strong><span>Tenaga<br>Pendidik</span></div><div><strong>100+</strong><span>Mitra<br>Industri</span></div><div><strong>1951</strong><span>Tahun<br>Berdiri</span></div></div>
        </section>

        <section id="jurusan" class="landing-wrap section-block"><div class="section-heading"><div><p class="landing-kicker"><span></span> Pilih jalurmu</p><h2>Belajar sesuatu yang<br><em>berguna.</em></h2></div><p>Sepuluh kompetensi keahlian. Satu tujuan: membuatmu siap melangkah dengan percaya diri.</p></div><div class="program-grid official-program-grid">
            <article class="program-card program-green"><span class="program-number">01</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/pplg.png') }}" alt="Logo PPLG" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>PPLG</h3><p>Pengembangan Perangkat Lunak dan Gim</p><a href="#ppdb" aria-label="Pelajari PPLG">↗</a></article>
            <article class="program-card program-lilac"><span class="program-number">02</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/dkv.png') }}" alt="Logo DKV" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>DKV</h3><p>Desain Komunikasi Visual</p><a href="#ppdb" aria-label="Pelajari DKV">↗</a></article>
            <article class="program-card program-sky"><span class="program-number">03</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/tjkt.png') }}" alt="Logo TJKT" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>TJKT</h3><p>Teknik Jaringan Komputer dan Telekomunikasi</p><a href="#ppdb" aria-label="Pelajari TJKT">↗</a></article>
            <article class="program-card program-orange"><span class="program-number">04</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/akl.png') }}" alt="Logo AKL" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>AKL</h3><p>Akuntansi dan Keuangan Lembaga</p><a href="#ppdb" aria-label="Pelajari AKL">↗</a></article>
            <article class="program-card program-cream"><span class="program-number">05</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/mplb.png') }}" alt="Logo MPLB" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>MPLB</h3><p>Manajemen Perkantoran dan Layanan Bisnis</p><a href="#ppdb" aria-label="Pelajari MPLB">↗</a></article>
            <article class="program-card program-dark"><span class="program-number">06</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/pm.png') }}" alt="Logo PM" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>PM</h3><p>Pemasaran</p><a href="#ppdb" aria-label="Pelajari Pemasaran">↗</a></article>
            <article class="program-card program-rose"><span class="program-number">07</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/tkf.png') }}" alt="Logo TKF" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>TKF</h3><p>Teknik Kejuruan Farmasi</p><a href="#ppdb" aria-label="Pelajari TKF">↗</a></article>
            <article class="program-card program-yellow"><span class="program-number">08</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/tlg.png') }}" alt="Logo TLG" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>TLG</h3><p>Teknik Logistik</p><a href="#ppdb" aria-label="Pelajari TLG">↗</a></article>
            <article class="program-card program-mint"><span class="program-number">09</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/tet.png') }}" alt="Logo TET" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>TET</h3><p>Teknik Energi Terbarukan</p><a href="#ppdb" aria-label="Pelajari TET">↗</a></article>
            <article class="program-card program-violet"><span class="program-number">10</span><span class="program-symbol"><img src="{{ asset('images/logo-jurusan/tlm.png') }}" alt="Logo TLM" onerror="this.src='{{ asset('images/image-2.png') }}'"></span><h3>TLM</h3><p>Teknik Laboratorium Medik</p><a href="#ppdb" aria-label="Pelajari TLM">↗</a></article>
        </div></section>

        <section id="fasilitas" class="landing-wrap facility-grid"><div class="facility-feature"><img src="/images/image-1.png" alt="Area hijau dan fasilitas sekolah"><div><p class="landing-kicker"><span></span> Fasilitas</p><h2>Tempat ide<br><em>berakar.</em></h2><p class="facility-caption">Laboratorium, bengkel, dan ruang kolaborasi yang membantu setiap ide tumbuh menjadi karya.</p></div></div><div class="facility-list"><div><span>01</span><strong>Lab & bengkel modern</strong><small>Praktik dengan standar industri</small></div><div><span>02</span><strong>Kemitraan industri</strong><small>Belajar dari dunia kerja yang nyata</small></div><div><span>03</span><strong>Komunitas berprestasi</strong><small>Teman tumbuh di setiap langkah</small></div><a class="landing-button landing-button-dark" href="#ppdb">Kunjungi sekolah <span>↗</span></a></div></section>

        <section id="ppdb" class="landing-wrap admission-grid"><div><p class="landing-kicker"><span></span> Penerimaan peserta didik baru</p><h2>Langkah pertama<br><em>dimulai di sini.</em></h2><p>Siap menemukan jalurmu? Simpan pertanyaan, cek persyaratan, dan mulai kenali SMKN 1 Garut lebih dekat.</p><a class="landing-button landing-button-primary" href="https://ppdb.jabarprov.go.id" target="_blank" rel="noopener noreferrer">Buka portal PPDB <span>↗</span></a></div><div class="admission-card"><div class="admission-top"><span>PPDB 2026 / 2027</span><span class="live-dot">● Pendaftaran online</span></div><h3>Yang perlu disiapkan</h3><ul><li><span>01</span> Ijazah atau SKL SMP/MTs</li><li><span>02</span> Kartu Keluarga dan akta kelahiran</li><li><span>03</span> Rapor semester 1 sampai 5</li><li><span>04</span> Pas foto berwarna</li></ul><div class="admission-foot">Jadwal mengikuti ketentuan PPDB Provinsi Jawa Barat <span>↗</span></div></div></section>
    </main>

    <footer id="kontak" class="landing-footer animated-footer"><div class="footer-marquee" aria-hidden="true"><div class="footer-marquee-track"><span class="footer-marquee-group">SMKN 1 GARUT <b>•</b> Motekar Wibawa Mukti <b>•</b> Belajar dengan rasa ingin tahu <b>•</b> Berkarya dengan keberanian <b>•</b> Tumbuh bersama Garut <b>•</b> Sepuluh jurusan untuk masa depan <b>•</b> Kompetensi bertemu karakter <b>•</b> Siap belajar, siap berkarya <b>•</b> Vokasi yang relevan dengan industri <b>•</b> Dari Garut untuk Indonesia</span><span class="footer-marquee-group">SMKN 1 GARUT <b>•</b> Motekar Wibawa Mukti <b>•</b> Belajar dengan rasa ingin tahu <b>•</b> Berkarya dengan keberanian <b>•</b> Tumbuh bersama Garut <b>•</b> Sepuluh jurusan untuk masa depan <b>•</b> Kompetensi bertemu karakter <b>•</b> Siap belajar, siap berkarya <b>•</b> Vokasi yang relevan dengan industri <b>•</b> Dari Garut untuk Indonesia</span></div></div><div class="landing-wrap footer-main"><div class="footer-intro"><a class="landing-brand footer-brand" href="#beranda"><img src="/images/image-2.png" alt="Logo SMKN 1 Garut"><span><strong>SMKN 1 Garut</strong><small>Motekar Wibawa Mukti</small></span></a><p>Sekolah vokasi yang menyiapkan generasi terampil, berkarakter, dan berdaya saing global sejak 1951.</p><div class="footer-socials" aria-label="Media sosial sekolah"><a href="https://www.instagram.com" target="_blank" rel="noopener noreferrer" aria-label="Instagram">ig</a><a href="https://www.youtube.com" target="_blank" rel="noopener noreferrer" aria-label="YouTube">▶</a><a href="https://www.tiktok.com" target="_blank" rel="noopener noreferrer" aria-label="TikTok">tk</a><a href="https://www.facebook.com" target="_blank" rel="noopener noreferrer" aria-label="Facebook">f</a></div></div><div class="footer-column"><span class="footer-label">Jelajahi</span><a href="#tentang">Tentang sekolah <span>↗</span></a><a href="#jurusan">10 jurusan <span>↗</span></a><a href="#fasilitas">Fasilitas <span>↗</span></a><a href="#ppdb">PPDB 2026/2027 <span>↗</span></a></div><div class="footer-location"><span class="footer-label">Temui kami</span><p>Jl. Cimanuk No. 309A<br>Sukagalih, Tarogong Kidul<br>Kabupaten Garut, Jawa Barat 44151</p><a class="map-link" href="https://www.google.com/maps/search/?api=1&query=SMKN+1+Garut+Jl.+Cimanuk+No.+309A" target="_blank" rel="noopener noreferrer">Buka Google Maps <span>↗</span></a></div></div><div class="landing-wrap footer-bottom"><span>© 2026 SMKN 1 Garut</span><span>Built with curiosity &bull; Motekar Wibawa Mukti</span></div></footer>

    <button class="public-chat-launcher" id="publicChatLauncher" type="button" aria-label="Buka AI Sahabat Sekolah"><span>✦</span><strong>Tanya AI</strong><small>Sahabat sekolah</small></button><section class="public-chat-window" id="publicChatWindow" aria-label="AI Sahabat Sekolah" aria-hidden="true"><header><div class="public-chat-avatar">✦</div><div><strong>Sahabat Sekolah</strong><small>AI informasi SMKN 1 Garut</small></div><button type="button" id="publicChatClose" aria-label="Tutup chat">×</button></header><div class="public-chat-body"><div class="public-chat-message public-chat-bot">Halo! Aku bisa bantu menjawab pertanyaan tentang jurusan, fasilitas, PPDB, dan kehidupan belajar di SMKN 1 Garut.</div><div class="public-chat-suggestions"><button type="button" data-public-question="Apa saja jurusan yang tersedia?">Jurusan yang tersedia</button><button type="button" data-public-question="Apa syarat PPDB?">Syarat PPDB</button></div><div class="public-chat-conversation" id="publicChatConversation"></div><form id="publicChatForm"><input id="publicChatInput" type="text" placeholder="Tulis pertanyaanmu..." autocomplete="off" maxlength="500"><button type="submit" aria-label="Kirim">↑</button></form></div></section>
</body>
</html>
