<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduCore | Ruang Guru</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
    <div class="student-shell">
        <aside class="sidebar"><div class="brand"><a class="brand-mark" href="{{ route('teacher.dashboard') }}">E</a><div><strong>EduCore</strong><small>Ruang guru SMKN 1 Garut</small></div></div><div class="side-label">Menu mengajar</div><nav><a class="side-link is-active" href="{{ route('teacher.dashboard') }}"><span>⌂</span>Ringkasan kelas</a><a class="side-link" href="{{ route('teacher.assignments') }}"><span>▤</span>Kelola tugas</a><a class="side-link" href="#"><span>▣</span>Jadwal mengajar</a><a class="side-link" href="#"><span>⌁</span>Input nilai</a></nav><div class="side-label" style="margin-top:30px;">Layanan</div><nav><a class="side-link" href="#"><span>▧</span>Pengajuan izin</a><a class="side-link" href="#"><span>▥</span>Materi belajar</a></nav><div class="side-bottom"><form action="{{ route('logout') }}" method="POST">@csrf<button class="side-link" type="submit"><span>↪</span>Keluar</button></form></div></aside>
        <main class="main-content"><header class="topbar"><div class="breadcrumb">Ruang guru / <strong>Ringkasan kelas</strong></div><div class="top-actions"><button class="icon-button" aria-label="Notifikasi"><span class="notification-dot"></span><svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg></button><div class="profile-chip"><div class="avatar">DS</div><div><strong>{{ auth()->user()->name }}</strong><small>Guru {{ auth()->user()->teacher_subject ?: 'Mata Pelajaran' }}</small></div></div></div></header><section class="welcome"><div><div class="eyebrow">RUANG GURU</div><h1>Selamat datang, {{ auth()->user()->name }}<span style="color:#4f8df5;">.</span></h1><p>Pantau ritme kelas dan tindak lanjut pembelajaran hari ini.</p></div><div class="date-badge">Semester Ganjil &nbsp;&bull;&nbsp; 2026/2027</div></section><section class="metric-grid"><div class="metric-card"><div class="metric-top"><span>Total siswa</span><span class="metric-icon">♙</span></div><div class="metric-value">{{ $studentCount }}</div><div class="metric-note">Siswa terdaftar</div></div><div class="metric-card"><div class="metric-top"><span>Tugas aktif</span><span class="metric-icon">▤</span></div><div class="metric-value">{{ $assignmentCount }}</div><div class="metric-note">Di semua kelas</div></div><div class="metric-card"><div class="metric-top"><span>Izin menunggu</span><span class="metric-icon">▧</span></div><div class="metric-value">{{ $pendingPermits }}</div><div class="metric-note">Perlu ditinjau</div></div><div class="metric-card"><div class="metric-top"><span>Kehadiran kelas</span><span class="metric-icon">✓</span></div><div class="metric-value">96<span style="font-size:15px;">%</span></div><div class="metric-note"><b>Stabil</b> minggu ini</div></div></section><section class="panel page-panel"><div class="panel-heading"><div><h2>Pengajuan izin terbaru</h2><p>Tinjau permohonan siswa dan tindak lanjuti seperlunya.</p></div><span class="soft-tag">{{ $pendingPermits }} menunggu</span></div><div class="data-list">@forelse ($recentPermits as $permit)<div class="permit-row"><div class="subject-icon mint">▧</div><div class="row-main"><h3>{{ $permit->student_name }} &nbsp;&bull;&nbsp; {{ $permit->type }}</h3><p>{{ $permit->permit_date->format('d M Y') }} &nbsp;&bull;&nbsp; {{ $permit->description }}</p></div><span class="status">{{ ucfirst($permit->status) }}</span></div>@empty<div class="empty-state">Belum ada pengajuan izin baru.</div>@endforelse</div></section></main>
    </div>
</body>
</html>
