@extends('layouts.perpustakaan')

@section('content')
<section class="perpus-hero perpus-reveal">
    <div><div class="perpus-kicker-row"><p class="perpus-kicker">RUANG BACA DIGITAL</p><span class="perpus-live-dot">Koleksi aktif</span></div><h1>Temukan buku yang membuatmu ingin tahu lebih jauh.</h1><p class="perpus-hero-copy">Cari koleksi berdasarkan judul, penulis, kategori, atau kode DDC.</p><div class="perpus-hero-actions"><a href="#catalog" class="perpus-action">Jelajah koleksi <span>↓</span></a><span class="perpus-hero-note">15+ bacaan pilihan untuk siswa SMK</span></div></div>
    <div class="perpus-hero-mark"><span>✦</span><small>READ<br>MORE</small></div>
</section>
<form method="GET" class="perpus-search perpus-reveal" id="catalogSearchForm"><span>⌕</span><input id="catalogSearch" name="q" value="{{ $search }}" placeholder="Ketik judul, penulis, kategori, atau DDC..." aria-label="Cari koleksi"><span class="perpus-search-live">LIVE</span><button type="submit">Cari koleksi <span>↗</span></button></form>
<div class="perpus-metrics perpus-reveal"><article><span class="perpus-metric-icon">▦</span><small>Total koleksi</small><strong>{{ number_format($totalBooks) }}</strong><span>eksemplar tersedia</span></article><article><span class="perpus-metric-icon">◷</span><small>Pinjaman aktif</small><strong>{{ $activeLoans }}</strong><span>perlu kamu pantau</span></article><article><span class="perpus-metric-icon">↺</span><small>Riwayat</small><strong>{{ $historyCount }}</strong><span>transaksi tercatat</span></article><article><span class="perpus-metric-icon">✦</span><small>Poin literasi</small><strong>{{ number_format($literacyPoints) }}</strong><span>terus bertumbuh</span></article></div>
<div class="perpus-section-head perpus-reveal" id="catalog"><div><p class="perpus-kicker">KATALOG PILIHAN</p><h2>Rak pengetahuan</h2></div><span id="catalogResult">{{ $books->total() }} judul ditemukan</span></div>
<nav class="perpus-category-scroll perpus-reveal" aria-label="Filter kategori"><a class="{{ $category === '' ? 'is-active' : '' }}" href="{{ route('library.catalog', request()->except('category', 'page')) }}">Semua koleksi</a>@foreach ($categories as $item)<a class="{{ $category === $item->slug ? 'is-active' : '' }}" href="{{ route('library.catalog', array_merge(request()->except('page'), ['category' => $item->slug])) }}">{{ $item->name }} <span>{{ $item->books_count }}</span></a>@endforeach</nav>
<div class="perpus-book-grid" id="bookGrid">
@forelse ($books as $book)
<article class="perpus-book-card perpus-reveal" data-book-card data-book-search="{{ strtolower($book->title.' '.$book->author.' '.$book->category->name.' '.$book->ddc_code.' '.$book->rack_location) }}">
    <a class="perpus-cover" href="{{ route('library.books.show', $book) }}" style="background-image: url('{{ $book->cover_image }}')"><span>{{ $book->category->name }}</span></a>
    <div class="perpus-book-body"><small>{{ $book->book_code }} · Rak {{ $book->rack_location }}</small><h3>{{ $book->title }}</h3><p>{{ $book->author }} · {{ $book->publish_year }}</p><div class="perpus-book-foot"><b class="{{ $book->available_stock ? 'is-available' : 'is-empty' }}">{{ $book->available_stock ? $book->available_stock.' tersedia' : 'Stok habis' }}</b><button class="perpus-detail-button" type="button" data-book-detail data-title="{{ $book->title }}" data-author="{{ $book->author }}" data-category="{{ $book->category->name }}" data-ddc="{{ $book->ddc_code ?: 'Belum diklasifikasikan' }}" data-rack="{{ $book->rack_location }}" data-stock="{{ $book->available_stock }}" data-synopsis="{{ $book->synopsis ?: 'Belum ada sinopsis untuk buku ini.' }}" data-cover="{{ $book->cover_image }}" data-loan-url="{{ auth()->user()->isStudent() && $book->available_stock ? route('library.loans.store', $book) : '' }}">Lihat detail <span>↗</span></button></div></div>
</article>
@empty <div class="perpus-empty">Belum ada buku yang cocok dengan pencarianmu.</div> @endforelse
</div>
<div class="perpus-catalog-no-results" id="catalogNoResults" hidden><strong>Buku belum ditemukan.</strong><span>Coba judul, penulis, kategori, atau kode DDC lain.</span></div>
<div class="perpus-pagination">{{ $books->links() }}</div>
<div class="perpus-modal" id="bookModal" aria-hidden="true"><div class="perpus-modal-backdrop" data-close-book-modal></div><div class="perpus-modal-card" role="dialog" aria-modal="true" aria-labelledby="bookModalTitle"><button class="perpus-modal-close" type="button" data-close-book-modal aria-label="Tutup detail">×</button><div class="perpus-modal-cover" id="bookModalCover"></div><div class="perpus-modal-content"><span class="perpus-kicker" id="bookModalCategory"></span><h2 id="bookModalTitle"></h2><p class="perpus-modal-author" id="bookModalAuthor"></p><p id="bookModalSynopsis"></p><div class="perpus-detail-grid"><span><small>DDC</small><b id="bookModalDdc"></b></span><span><small>Lokasi rak</small><b id="bookModalRack"></b></span><span><small>Ketersediaan</small><b id="bookModalStock"></b></span></div><div id="bookModalAction"></div></div></div></div>
@endsection
