@extends('layouts.perpustakaan')

@section('content')
<section class="perpus-landing-hero perpus-reveal">
    <div class="perpus-landing-copy"><div class="perpus-kicker-row"><p class="perpus-kicker">SMKN 1 GARUT · DIGITAL LIBRARY</p><span class="perpus-live-dot">Open today</span></div><h1>Ruang kecil untuk ide-ide besar.</h1><p>Temukan bacaan yang membantu kamu belajar, membuat, dan melihat dunia dengan sudut pandang baru.</p><div class="perpus-role-callout"><span>{{ auth()->user()->role === 'student' ? '◒' : (auth()->user()->role === 'teacher' ? '◉' : '◆') }}</span><div><b>{{ auth()->user()->role === 'student' ? 'Ruang belajar siswa' : (auth()->user()->role === 'teacher' ? 'Ruang paket kelas guru' : 'Ruang kendali petugas') }}</b><small>{{ auth()->user()->role === 'student' ? 'Ajukan buku dan pantau deadline pinjaman.' : (auth()->user()->role === 'teacher' ? 'Siapkan referensi untuk kegiatan belajar kelas.' : 'Kelola persetujuan dan pengembalian koleksi.') }}</small></div></div><div class="perpus-landing-actions"><a class="perpus-action" href="{{ route('library.catalog') }}">Mulai menjelajah <span>↗</span></a>@if (auth()->user()->isTeacher())<a class="perpus-text-link" href="{{ route('library.class-loans') }}">Paket kelas</a>@elseif (auth()->user()->role === 'admin')<a class="perpus-text-link" href="{{ route('library.admin.circulation') }}">Buka sirkulasi</a>@else<a class="perpus-text-link" href="{{ route('library.profile') }}">Lihat kartu anggota</a>@endif</div><div class="perpus-landing-trust"><span>✦</span><span>15+ koleksi pilihan</span><i></i><span>Single account EduCore</span></div></div>
    <div class="perpus-landing-art"><div class="perpus-orbit orbit-a"></div><div class="perpus-orbit orbit-b"></div><div class="perpus-orb orb-cyan"></div><div class="perpus-orb orb-mint"></div><div class="perpus-orb orb-lilac"></div><div class="perpus-orb orb-tiny orb-tiny-one"></div><div class="perpus-orb orb-tiny orb-tiny-two"></div><div class="perpus-floating-book book-one"><b>005.13</b><span>Pemrograman Web Modern</span></div><div class="perpus-floating-book book-two"><b>813</b><span>Laskar Pelangi</span></div><div class="perpus-art-core"><span>EP</span><small>READ<br>CREATE<br>GROW</small></div></div>
</section>
<section class="perpus-landing-stats perpus-reveal"><article><strong>{{ number_format($collectionCount) }}+</strong><span>eksemplar tersedia</span></article><article><strong>{{ $categoryCount }}</strong><span>rak pengetahuan</span></article><article><strong>7 hari</strong><span>durasi pinjaman siswa</span></article><article><strong>∞</strong><span>rasa ingin tahu</span></article></section>
<section class="perpus-landing-section perpus-reveal"><div class="perpus-section-head"><div><p class="perpus-kicker">PILIHAN HARI INI</p><h2>Mulai dari satu halaman.</h2></div><a class="perpus-text-link" href="{{ route('library.catalog') }}">Lihat semua koleksi ↗</a></div><div class="perpus-featured-grid">@foreach ($featuredBooks as $book)<a class="perpus-featured-card" href="{{ route('library.catalog') }}"><div class="perpus-featured-cover" style="background-image:url('{{ $book->cover_image }}')"><span>{{ $book->category->name }}</span></div><div><small>{{ $book->ddc_code }}</small><h3>{{ $book->title }}</h3><p>{{ $book->author }}</p></div></a>@endforeach</div></section>
@endsection
